language: python
python:
  - "2.7"
# before install commands
# Setup anaconda
before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda/bin:$PATH
# update conda
  - conda update --yes conda
# commands to install
install:
  - conda install --yes python=2.7 numpy
  - pip install fuzzpy
# command to run tests
script:
  - python -m unittest discover -v
# command for email notifications, set to no notifications via email
notifications:
    email: false
