language: python
python:
  - "2.7"
# command to install dependencies
install:
  - pip install unittest
# command to run tests
script:
  - python -v test_biom_calc.py 
# command for email notifications, set to no notifications via email
notifications:
    email: false