language: python
python:
  - "2.7"
# command to install
install:
  - pip install fuzzpy
# command to run tests
script:
  - python -m unittest discover -v
# command for email notifications, set to no notifications via email
notifications:
    email: false
