cache: apt
sudo: false
language: python
python:
  - "2.7"
  - "3.4"
addons:
  apt:
    packages:
    - libatlas-dev
    - libatlas-base-dev
    - liblapack-dev
    - gfortran
before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda update --yes conda
install:
  - conda install --yes python=$TRAVIS_PYTHON_VERSION pip numpy scipy
  - conda update numpy scipy
  - pip install pep8 python-coveralls biom-format
  - pip install .

script:
  - python -m unittest discover -s phylotoast/test/ -p test_biom_calc.py -vf
  - coverage report -m phylotoast/test/test_biom_calc.py
  - python -m unittest discover -s phylotoast/test/ -p test_util.py -vf
  - coverage report -m phylotoast/test/test_util.py

after_success:
  - coveralls

# command for email notifications, set to no notifications via email
notifications:
    email: false
